title: IPFB Projects
description: >- 
  List projects made in ifpb

# Build settings
markdown: kramdown

theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
